// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArYLt2lboYL_aVJ3JK5X3kI9wDqPK9P6Q',
    appId: '1:496335022424:web:cfce3f9ebdb81c9d0bdd2d',
    messagingSenderId: '496335022424',
    projectId: 'film-ku-33f66',
    authDomain: 'film-ku-33f66.firebaseapp.com',
    storageBucket: 'film-ku-33f66.appspot.com',
    measurementId: 'G-LLS8F0H97C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQTUWA1SpAQOr-XPkEgIFCUQJB9zalkv0',
    appId: '1:496335022424:android:7bf8e2aa232bff6a0bdd2d',
    messagingSenderId: '496335022424',
    projectId: 'film-ku-33f66',
    storageBucket: 'film-ku-33f66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzNs3Avo7VXoES4RramCZsiw7avtDz7h0',
    appId: '1:496335022424:ios:00272b3405e030110bdd2d',
    messagingSenderId: '496335022424',
    projectId: 'film-ku-33f66',
    storageBucket: 'film-ku-33f66.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
